"""
Multi-Model Reasoning Engine - Professional LLM Engine for Medical Triage

Features:
- Real-time Local LLM inference (Llama, DeepSeek, Mistral, etc.)
- Structured JSON output via GBNF Grammars
- Smart Dynamic Token Scaling (Auto-retries if output is cut off)
- Anti-Hallucination Prompts
- Markdown-Formatted Output for Frontend
- Full Backend Logging

Usage:
    engine = get_engine()
    response = engine.answer_staff_question("Why is this high risk?", patient_data)
"""

import os
import gc
import threading
import logging
import json
import re
from typing import Dict, List, Any, Tuple, Optional
from dataclasses import dataclass
from datetime import datetime

# Pydantic defines the strict schema for the model's output
from pydantic import BaseModel, Field, ConfigDict

logger = logging.getLogger(__name__)

# Path to LLM output log file (append mode)
LLM_LOG_PATH = os.path.join(os.path.dirname(__file__), "backend.log")

# Import your existing registry
from model_registry import (
    SUPPORTED_MODELS,
    ModelConfig,
    get_model_config,
    get_all_models,
    model_to_dict,
    DEFAULT_MODEL_ID,
)

# =============================================================================
# 1. LOGGING UTILITY
# =============================================================================

def log_llm_output(raw_output: str, context: str = ""):
    """Logs the raw text generated by the LLM to backend.log."""
    try:
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        log_entry = (
            f"\n{'='*60}\n"
            f"[{timestamp}] RAW MODEL OUTPUT ({context})\n"
            f"{'-'*60}\n"
            f"{raw_output}\n"
            f"{'='*60}\n"
        )
        with open(LLM_LOG_PATH, "a", encoding="utf-8") as f:
            f.write(log_entry)
    except Exception as e:
        print(f"Warning: Logging failed: {e}")

# =============================================================================
# 2. DEFINE OUTPUT SCHEMA (Markdown Enabled)
# =============================================================================

class TriageResponse(BaseModel):
    """
    Strict schema ensuring the LLM output matches Frontend UI sections.
    """
    model_config = ConfigDict(protected_namespaces=())

    reasoning: str = Field(
        ..., 
        description="Internal clinical thinking process. Analyze the provided symptoms and risk factors."
    )
    answer: str = Field(
        ..., 
        description="Direct answer to the user. MUST use Markdown formatting (bold **text**, bullet points -, and \\n newlines) for clear readability."
    )
    follow_up_questions: List[str] = Field(
        ..., 
        description="3 distinct follow-up questions to ask the patient.",
        min_items=1,
        max_items=5
    )

# =============================================================================
# 3. ENGINE SETUP & DATA STRUCTURES
# =============================================================================

try:
    from llama_cpp import Llama, LlamaGrammar
    LLAMA_AVAILABLE = True
except ImportError:
    LLAMA_AVAILABLE = False
    print("CRITICAL WARNING: llama-cpp-python not installed. Engine will run in fallback mode.")

@dataclass
class LoadedModel:
    model_id: str
    config: ModelConfig
    instance: Any
    loaded_at: datetime
    inference_count: int = 0

class MultiModelEngine:
    def __init__(
        self, 
        models_dir: str, 
        default_model_id: str = DEFAULT_MODEL_ID, 
        auto_load: bool = True
    ):
        self.models_dir = models_dir
        self.default_model_id = default_model_id
        self._current_model: Optional[LoadedModel] = None
        self._lock = threading.RLock()
        
        # Initialize Counters (Preserved)
        self._total_inferences = 0
        self._model_switches = 0
        
        # Inference Configuration
        self.n_gpu_layers = int(os.environ.get("N_GPU_LAYERS", "-1")) 
        self.n_threads = int(os.environ.get("N_THREADS", "6")) 

        # Grammar Compilation
        self.json_grammar = None
        if LLAMA_AVAILABLE:
            try:
                schema = TriageResponse.model_json_schema()
                self.json_grammar = LlamaGrammar.from_json_schema(json.dumps(schema))
                print("GBNF Grammar compiled successfully.")
            except Exception as e:
                print(f"Failed to compile grammar: {e}")

        if auto_load:
            self._try_load_default_model()

    # =========================================================================
    # Model Management
    # =========================================================================

    def _try_load_default_model(self):
        if self._model_exists(self.default_model_id):
            self.load_model(self.default_model_id)
            return
        for model_id in SUPPORTED_MODELS:
            if self._model_exists(model_id):
                print(f"Default not found. Loading {model_id}...")
                self.load_model(model_id)
                return
        print("No models found. Engine running in fallback mode.")

    def _model_exists(self, model_id: str) -> bool:
        config = get_model_config(model_id)
        return bool(config and os.path.exists(os.path.join(self.models_dir, config.filename)))

    def load_model(self, model_id: str) -> bool:
        if not LLAMA_AVAILABLE: return False
        config = get_model_config(model_id)
        if not config: return False
        
        path = os.path.join(self.models_dir, config.filename)

        with self._lock:
            if self._current_model and self._current_model.model_id == model_id:
                return True 

            self.unload_model()
            try:
                print(f"Loading model: {config.name}...")
                
                layers = self.n_gpu_layers
                if layers == -1: 
                    layers = config.recommended_gpu_layers or -1

                instance = Llama(
                    model_path=path, 
                    n_ctx=4096, 
                    n_threads=self.n_threads,
                    n_gpu_layers=layers,
                    verbose=False
                )
                self._current_model = LoadedModel(model_id, config, instance, datetime.now())
                self._model_switches += 1
                return True
            except Exception as e:
                print(f"Failed to load {model_id}: {e}")
                return False

    def unload_model(self):
        with self._lock:
            if self._current_model:
                try:
                    del self._current_model.instance
                    gc.collect()
                except: pass
                self._current_model = None

    def switch_model(self, model_id: str) -> bool:
        return self.load_model(model_id)

    def get_current_model(self) -> Optional[Dict[str, Any]]:
        with self._lock:
            if not self._current_model: return None
            return {
                "model_id": self._current_model.model_id,
                "id": self._current_model.model_id,
                "name": self._current_model.config.name,
                "loaded_at": self._current_model.loaded_at.isoformat(),
                "inference_count": self._current_model.inference_count
            }

    # =========================================================================
    # Core Generation Logic (Robust)
    # =========================================================================

    def _construct_system_prompt(self, patient_data: str) -> str:
        """
        Instructions explicitly demand Markdown and JSON.
        """
        return (
            "You are an expert medical triage assistant. Analyze the patient data below.\n\n"
            f"### PATIENT DATA\n{patient_data}\n\n"
            "### INSTRUCTIONS\n"
            "1. Answer the User Query based strictly on the Patient Data.\n"
            "2. **FORMATTING:** The 'answer' field MUST use **Markdown**.\n"
            "   - Use **bold** for key risks.\n"
            "   - Use `\\n` for new lines/paragraphs.\n"
            "   - Use bullet points (`-`) for lists.\n"
            "3. Provide detailed medical reasoning.\n"
            "4. Suggest 3 relevant follow-up questions.\n"
            "5. Output must be valid JSON."
        )

    def _repair_json(self, json_str: str) -> Dict[str, Any]:
        """Robust JSON repair for cut-off or doubled output."""
        json_str = json_str.strip()
        
        # Strategy 1: Detect Restarts
        if json_str.count('"reasoning":') > 1:
            last_start = json_str.rfind('{')
            if '"reasoning":' in json_str[last_start:]:
                json_str = json_str[last_start:]

        # Strategy 2: Attempt standard Parse
        try:
            return json.loads(json_str)
        except json.JSONDecodeError as e:
            if e.msg.startswith("Extra data"):
                try: return json.loads(json_str[:e.pos])
                except: pass

        # Strategy 3: Fix Truncation
        quote_count = len(re.findall(r'(?<!\\)"', json_str))
        if quote_count % 2 != 0: json_str += '"'
        json_str = re.sub(r',\s*([\]}])', r'\1', json_str)
        
        open_brackets = json_str.count('[')
        close_brackets = json_str.count(']')
        json_str += ']' * (open_brackets - close_brackets)
        
        open_braces = json_str.count('{')
        close_braces = json_str.count('}')
        json_str += '}' * (open_braces - close_braces)

        try:
            return json.loads(json_str)
        except:
            return {
                "reasoning": "Model output was malformed and could not be repaired.",
                "answer": "I encountered an internal error processing the response.",
                "follow_up_questions": ["Please try asking again."]
            }

    def _generate_structured(
        self, 
        patient_context: Dict[str, Any], 
        user_query: str, 
        temperature: float = 0.6,
        base_max_tokens: int = 1500
    ) -> Dict[str, Any]:
        """
        Smart Generation with Dynamic Token Scaling & Markdown instructions.
        """
        with self._lock:
            if not self._current_model or not self.json_grammar:
                return self._fallback_response("Engine not ready.")

            data_str = json.dumps(patient_context, indent=2)
            system_msg = self._construct_system_prompt(data_str)
            
            prompt = (
                f"<|im_start|>system\n{system_msg}<|im_end|>\n"
                f"<|im_start|>user\n{user_query}<|im_end|>\n"
                f"<|im_start|>assistant\n"
            )

            # Retry Logic for Length
            attempts = [(base_max_tokens, "Standard"), (3500, "Extended")]
            last_error = None

            for max_tokens, mode in attempts:
                try:
                    output = self._current_model.instance(
                        prompt,
                        max_tokens=max_tokens,
                        temperature=temperature,
                        top_p=0.9,
                        repeat_penalty=1.1,
                        grammar=self.json_grammar, 
                        stop=["<|im_end|>", "}"], 
                        echo=False
                    )
                    
                    self._current_model.inference_count += 1
                    self._total_inferences += 1
                    
                    finish_reason = output['choices'][0]['finish_reason']
                    raw_text = output['choices'][0]['text']
                    
                    # LOGGING (Preserved)
                    log_llm_output(raw_text, context=f"Structured Generation ({mode})")

                    if finish_reason == "length" and mode == "Standard":
                        logger.warning("Token limit hit. Extending...")
                        continue

                    clean_text = raw_text.strip()
                    if "```" in clean_text: 
                        clean_text = clean_text.replace("```json", "").replace("```", "").strip()

                    return self._repair_json(clean_text)

                except Exception as e:
                    last_error = e
                    logger.error(f"Generation attempt failed: {e}")

            return self._fallback_response(str(last_error))

    def _fallback_response(self, error_msg: str) -> Dict[str, Any]:
        return {
            "reasoning": f"System Alert: {error_msg}",
            "answer": "Unable to process request. Please consult clinical protocols manually.",
            "follow_up_questions": ["Is the patient stable?", "Check system logs."]
        }

    # =========================================================================
    # Public API
    # =========================================================================

    def generate_summary(
        self, 
        clinical_state: Dict[str, Any], 
        model_id: Optional[str] = None
    ) -> Tuple[str, List[str]]:
        if model_id: self.switch_model(model_id)
        
        response = self._generate_structured(
            clinical_state, 
            "Provide a concise clinical triage summary."
        )
        
        flags = self._extract_key_flags(clinical_state)
        # We can log reasoning here too if needed
        return response.get("answer", "No summary."), flags

    def answer_staff_question(
        self, 
        question: str, 
        clinical_state: Dict[str, Any], 
        model_id: Optional[str] = None
    ) -> Dict[str, Any]:
        if model_id: self.switch_model(model_id)
        
        response = self._generate_structured(clinical_state, question)
        
        return {
            "answer": response["answer"],
            "reasoning": response["reasoning"],
            "suggested_questions": response["follow_up_questions"],
            "has_reasoning": True,
            "cited_data": self._extract_citations(response["answer"], clinical_state),
            "model_used": self._current_model.config.name if self._current_model else "Fallback"
        }

    # =========================================================================
    # Helpers
    # =========================================================================

    def _extract_key_flags(self, clinical_state: Dict[str, Any]) -> List[str]:
        flags = []
        demo = clinical_state.get("demographics", {})
        answers = clinical_state.get("answers", {})
        
        age = demo.get("age", 0)
        if age < 2: flags.append("Infant (< 2y)")
        elif age > 65: flags.append("Elderly (> 65y)")
        if demo.get("pregnant"): flags.append("Pregnant")
        
        for k, v in answers.items():
            if "fever" in k and isinstance(v, (int, float)) and v > 38: 
                flags.append(f"Fever ({v})")
            if "pain" in k and isinstance(v, (int, float)) and v >= 8: 
                flags.append("Severe Pain")
        
        for rule in clinical_state.get("triggered_rules", []):
            if rule.get("band") == "red": 
                flags.append(f"RED: {rule.get('description')}")
        return flags

    def _extract_citations(self, text: str, data: Dict[str, Any]) -> List[str]:
        citations = []
        t_low = text.lower()
        for k, v in data.get("answers", {}).items():
            if str(v).lower() in t_low: citations.append(f"{k}: {v}")
        for rule in data.get("triggered_rules", []):
            if rule.get("description", "").lower() in t_low: 
                citations.append(f"Rule: {rule.get('description')}")
        return citations[:5]

    def get_available_models(self) -> List[Dict]:
        return [
            {
                **model_to_dict(c), 
                "is_available": self._model_exists(c.id), 
                "is_loaded": (self._current_model and self._current_model.model_id == c.id)
            } 
            for c in get_all_models()
        ]

    def get_engine_stats(self) -> Dict:
        return {
            "llama_available": LLAMA_AVAILABLE,
            "current_model": self._current_model.config.name if self._current_model else None,
            "total_inferences": self._total_inferences
        }
    
    @property
    def is_loaded(self) -> bool: 
        return self._current_model is not None

_engine_instance: Optional[MultiModelEngine] = None

def get_engine(
    models_dir: str = "../models", 
    default_model_id: str = DEFAULT_MODEL_ID, 
    reinitialize: bool = False
) -> MultiModelEngine:
    global _engine_instance
    if _engine_instance is None or reinitialize:
        if _engine_instance and reinitialize: 
            _engine_instance.unload_model()
        _engine_instance = MultiModelEngine(models_dir, default_model_id)
    return _engine_instance

if __name__ == "__main__":
    print("=== Engine Test ===")
    eng = MultiModelEngine("../models", auto_load=True)
    if eng.is_loaded:
        test_case = {
            "demographics": {"age": 55, "sex": "male"},
            "answers": {"pain": 8, "location": "chest"},
            "risk_band": "red"
        }
        res = eng.answer_staff_question("Why is this urgent?", test_case)
        print(json.dumps(res, indent=2))